---

- hosts: core_01
  gather_facts: False
  connection: local
  roles:
    - core_01
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      #authorize: true
      #auth_pass: "{{ enable_password }}"
