---

- hosts: l2edge_01
  gather_facts: False
  connection: local
  roles:
    - l2edge_01
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      authorize: true
      auth_pass: "{{ enable_password }}"
