---

- hosts: l3edge_02
  gather_facts: False
  connection: local
  roles:
    - l3edge_02
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      #authorize: true
      #auth_pass: "{{ enable_password }}"
